#@ load("@ytt:data", "data")
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.data.packaging.carvel.dev
spec:
  group: data.packaging.carvel.dev
  groupPriorityMinimum: 100
  version: v1alpha1
  versionPriority: 100
  service:
    name: packaging-api
    namespace: #@ data.values.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: packaging-api
  namespace: #@ data.values.namespace
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: api
  selector:
    app: kapp-controller
