
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: installedpackages.install.package.carvel.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.packageRef.publicName
    description: Package public name
    name: Package name
    type: string
  - JSONPath: .status.version
    description: Package version
    name: Package version
    type: string
  - JSONPath: .status.friendlyDescription
    description: Friendly description
    name: Description
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: Time since creation
    name: Age
    type: date
  group: install.package.carvel.dev
  names:
    kind: InstalledPackage
    listKind: InstalledPackageList
    plural: installedpackages
    shortNames:
    - ipkg
    singular: installedpackage
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        spec:
          properties:
            cluster:
              properties:
                kubeconfigSecretRef:
                  properties:
                    key:
                      type: string
                    name:
                      type: string
                  type: object
                namespace:
                  type: string
              type: object
            packageRef:
              properties:
                publicName:
                  type: string
                version:
                  type: string
                versionSelection:
                  properties:
                    constraints:
                      type: string
                    prereleases:
                      properties:
                        identifiers:
                          items:
                            type: string
                          type: array
                      type: object
                  type: object
              type: object
            serviceAccountName:
              type: string
            values:
              items:
                properties:
                  secretRef:
                    properties:
                      key:
                        type: string
                      name:
                        type: string
                    type: object
                type: object
              type: array
          type: object
        status:
          properties:
            conditions:
              items:
                description: TODO rename to Condition
                properties:
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, this should be a short, machine understandable
                      string that gives the reason for condition's last transition.
                      If it reports "ResizeStarted" that means the underlying persistent
                      volume is being resized.
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            friendlyDescription:
              type: string
            observedGeneration:
              format: int64
              type: integer
            usefulErrorMessage:
              type: string
            version:
              description: TODO this is desired resolved version (not actually deployed)
              type: string
          required:
          - conditions
          - friendlyDescription
          - observedGeneration
          type: object
      required:
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
