#@data/values
---
namespace: kapp-controller
packaging_global_namespace: kapp-controller-packaging-global
create_namespace: true
create_packaging_namespace: true

dangerous_enable_pprof: false

push_images: false
image_cache: true
image_repo: docker.io/k14stest/kapp-controller-test

api_port: 10350
