name: Kind Cluster E2E tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          kubectl_version: v1.25.0
          cluster_name: kinder
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3 # default version of go is 1.10
        with:
          go-version: "1.19.6"
      - name: Install Carvel Tools
        run: ./hack/install-deps.sh
      # Run benchmark with `go test -bench` and stores the output to a file
      - name: Install kc and run e2e tests on kind
        run: |
          set -e -x
          kubectl version --short

          source ./hack/version-util.sh

          ytt -f config/ -v kapp_controller_version="$(get_kappctrl_ver)+develop" | kbld -f- > kbld.out 2> kbldmeta.out
          cat kbldmeta.out | tail -n 1 | sed 's/.*final: kapp-controller -> \(.*\)$/\1/p'  | tail -n 1 | xargs kind load docker-image --name kinder
          kapp deploy -a kc -f kbld.out -c -y

          export KAPPCTRL_E2E_SECRETGEN_CONTROLLER=true
          source ./hack/secretgen-controller.sh
          deploy_secretgen-controller

          mkdir tmp
          KAPPCTRL_E2E_NAMESPACE=kappctrl-test eval './hack/test-e2e.sh'
