name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v3.1.0
      - name: misspell
        uses: reviewdog/action-misspell@fe8d5c98c3761ef40755a7bb95460b2a33f6b346 # v1.1.0
        with:
          fail_on_error: true
          locale: "US"
          exclude: |
            ./vendor/*
            ./cli/vendor/*
            *generated*
            ./examples/cert-manager-tce-pkg/bundle/*
