name: reviewdog
on: [pull_request]
jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v3.0.1
      - name: misspell
        uses: reviewdog/action-misspell@bc3ad2d435c695c1955d4e2e1c3f1762fc6d57dc # v1.1.0
        with:
          fail_on_error: true
          locale: "US"
          exclude: |
            ./vendor/*
            ./cli/vendor/*
            *generated*
